### ISSUE TITLE
【Design Spec】フォント

### ISSUE THREAD

**Issue by indif78** [uplinkjp/uplink.co.jp#10]
## デフォルト（日本語）

- Yaku Han JP
- Noto Sans JP Regular
- Noto Sans JP Bold

Yaku Han JP は「YakuHanJP ゴシック体（約物全部入り）」でお願いします。
https://qrac.github.io/yakuhanjp/

Noto Sans JP、晴れてアーリーアクセスから本リスト入りしました。
こちらから参照お願いします。
https://fonts.google.com/specimen/Noto+Sans+JP

## 欧文見出しや日付など

- Space Grotesk Bold

ドライブ上の _spec/fonts/ 内にWOFF/WOFF2データを保管しています。
 
## 留意点

- デフォルトフォントの`font-family`にSpace Groteskを併記して合成フォントにする必要はありません。Noto Sans JPの文章内欧文はNoto Sansが適用される形でOKです。

- フォールバックは Macデバイス > Winデバイス > sans-serif の順になっていれば特にこだわりはありません。

- グロナビの汎用ボタン（グレー）、会員ログインボタン（黒）、UPLINK関連サービスボタンなどの日本語に長体（88%）をかけています。こちらは`transform: scaleX(.88); transform-origin: left center`とするなどして対応してくださいませ。

**Comment by uunnee** [comment]
@indif78 
こちら対応完了しておりますのでご確認お願いします〜！

**Comment by indif78** [comment]
@uunnee 
こちらも確認できましたので、クローズしますー
