### ISSUE TITLE
【Design Spec】グロナビの各種仕様

### ISSUE THREAD

**Issue by indif78** [uplinkjp/uplink.co.jp#13]
グロナビの各種仕様をまとめました。

## 参照データ

https://drive.google.com/drive/folders/1q8zjRc4WhSZSU_Yv9xkMYX_j2erM2XsV?usp=sharing

## ヘッダーの表示ルール

1. 各サイトのトップページ最上部（ファーストビュー）ではグロナビが一覧できる状態です（メニューアイコンもベタ塗りの状態）（uplink_globalnav_1）
2. スクロールダウン時は特になにも起きません（uplink_globalnav_2）
3. ページ途中（グロナビエリア以下）でスクロールアップすると、ヘッダーバーがスライドダウンで現れます（メニューアイコンは罫線のみ）（uplink_globalnav_3〜4）
4. メニューアイコンをタップすると、まず背景がシュッとViewport一杯の高さに伸びます（このタイミングでメニューアイコンはベタ塗りになる）（uplink_globalnav_5）
5. 続いてメニューボタンが順番に（タイミングをわずかにずらしながら）フェードインで表示されていきます（4〜5までのアニメーションは1秒程度で完了するイメージです）（uplink_globalnav_6〜7）
6. 再びメニューアイコンをタップするとメニューが閉じますが、その際のアニメーション時間は0.3〜0.5秒と短くなるイメージです

## ブレイクポイントごとのメニューレイアウト

- メニューボタンの並び方がブレイクポイントごと変わる想定です（uplink_*_pc, uplink_*_tab）
- このようにブロック的な積み方ができるよう、各ボタンの高さをデザイン通りに固定し、幅のみが画面幅に応じて変動するようにしてください
- 吉祥寺はカフェがなく、その分地図ボタンの幅が伸びますのでご注意ください

**Comment by indif78** [comment]
※「スワイプ」の表現が間違っていた（逆になっていた）ので、上記コメントおよびデータ上も「スクロール」で統一しておきました。意図は伝わっていたかと思いますが、念のため。

**Comment by indif78** [comment]
@uunnee 
こちら優先度は低めでOKですが、フロントが仕上がるまでのタイミングで：

> 4. メニューアイコンをタップすると、まず背景がシュッとViewport一杯の高さに伸びます（このタイミングでメニューアイコンはベタ塗りになる）（uplink_globalnav_5）
> 5. 続いてメニューボタンが順番に（タイミングをわずかにずらしながら）フェードインで表示されていきます（4〜5までのアニメーションは1秒程度で完了するイメージです）（uplink_globalnav_6〜7）
> 6. 再びメニューアイコンをタップするとメニューが閉じますが、その際のアニメーション時間は0.3〜0.5秒と短くなるイメージです

あたりの反映をお願いします。

**Comment by uunnee** [comment]
@indif78 
何点か確認させてください。

> メニューアイコンをタップすると、まず背景がシュッとViewport一杯の高さに伸びます（このタイミングでメニューアイコンはベタ塗りになる）（uplink_globalnav_5）

こちらはSPのみでしょうか？？

> 続いてメニューボタンが順番に（タイミングをわずかにずらしながら）フェードインで表示されていきます（4〜5までのアニメーションは1秒程度で完了するイメージです）（uplink_globalnav_6〜7）

こちらなのですが、
PC / TB / SPで並び順が違う都合上、
DOMの順序と表示されている順序が違うので、
上から順番にフェードインさせるのが難しいです。

全体を一気にフェードインか、上からグラデーション状にフェードインという形にさせていただけないでしょうか。
ご検討お願いいたします。

**Comment by uunnee** [comment]
- [ ] SPのみViewport一杯で、Tab/PCはそれぞれ成り行きの高さで展開する形でお願いします。
- [ ] ボタン（と検索エリア）のフェードインタイミングをランダムにすることは可能でしょうか？
- [ ] グロナビアイコンON OFF逆

**Comment by uunnee** [comment]
@indif78 
http://static.uplink.co.jp/
メインナビに関しまして、
https://github.com/uplinkjp/uplink.co.jp/issues/13#issuecomment-439590768 の内容を調整しました。
ご確認よろしくお願いいたします。

**Comment by indif78** [comment]
@uunnee 
こちら調整ありがとうございます！
確認できましたのでクローズしますー
