### ISSUE TITLE
【Design Spec】スケジュールエリアの日付バーSticky仕様

### ISSUE THREAD

**Issue by indif78** [uplinkjp/uplink.co.jp#14]
スケジュールエリアの日付バーはSticky的な挙動となるよう、実装をお願いします。

## 参照データ

https://drive.google.com/drive/folders/1TbTh3UEHsneHIY-q3KWAoCGF97QHOH0F?usp=sharing

## Sticky仕様

1. スケジュールエリアがViewport内に入り、最初の日付バーがViewportの上端に接したタイミングで固定表示に切り替わります（schedule-sticky1〜2）
2. 次の日付バーが前の日付バーに接触したタイミングで前の日付バーが押し出されはじめます（schedule-sticky3〜5）
3. 次の日付バーがViewportの上端に接したタイミングでこちらが固定表示になります（schedule-sticky6〜7）
4. 尚、スケジュールエリア内においても、スクロールアップした際はグローバルヘッダーがスライドダウンして覆いかぶさるようにお願いします（schedule-sticky8〜9）

**Comment by indif78** [comment]
@uunnee 
このようなSticky仕様、サイト全体的に利用する場面が多々ありそうです。
汎用的に扱えるよう管理しておいていただけるとよさそうです。
なんとなく念頭に置いておいてくださいませ〜

例）一覧ページが縦長になるような場合にセクションタイトルがStickyになり、今表示されているのが何の一覧なのかがより視覚的になるよう

**Comment by indif78** [comment]
※「スワイプ」の表現が間違っていた（逆になっていた）ので、上記コメントおよびデータ上も「スクロール」で統一しておきました。意図は伝わっていたかと思いますが、念のため。

**Comment by uunnee** [comment]
@indif78 
おまとめありがとうございました！
こちら対応完了しておりますのでご確認お願いします〜！

**Comment by indif78** [comment]
@uunnee 
こちらご対応ありがとうございました！
気になる点が出てきましたら改めて起票するようにいたします。
本イシューはクローズしますー
