### ISSUE TITLE
【Design Spec】サブナビのUI仕様

### ISSUE THREAD

**Issue by indif78** [uplinkjp/uplink.co.jp#41]
@uunnee Cc: @mcatm 
サブナビのUI仕様についてスペックをまとめました。
お手数をおかけしますが、下記内容で実装のほどお願いいたします。

https://drive.google.com/drive/folders/1fI41UsmKLB5v3LiW5ZOIZq_cTdE3mONr

## Viewport内にページヘッダー（ヘッダー下の色付きエリア）が表示されている場合（uplink_subnav_top0_1）

- カテゴリタイトル右の3点ボタンをタップすると（uplink_subnav_top0_2）
- サブナビリストがスライドダウンして（uplink_subnav_top0_3）
- 続くコンテンツも押し下げられる形で表示される（uplink_subnav_top0_4）

スペック画像ではページロード時サブナビが折りたたまれているSPサイズを例にしていますが、ロード時にサブナビが展開しているTab/PCサイズでは逆の動作となります。

## Viewport内にページヘッダーが表示されていない場合（uplink_subnav_3）

- サブナビがあるページを表示（uplink_subnav_1）
- スクロールダウン（uplink_subnav_2）
- ページヘッダーがViewportの外へ出たタイミングで画面下から三点ボタンがスライドアップ（uplink_subnav_3）
- その三点ボタンをタップすると（uplink_subnav_4）
- 画面下からサブナビを含むページヘッダーエリアがスライドアップ（中身はフェードイン）し、画面上からはグローバルヘッダーがスライドダウン（uplink_subnav_5）
- トランジション完了（uplink_subnav_6）

上記についてタブレットサイズ表示も参考用に作成してあります（uplink_subnav_tab_*）。
スライドアップしてくる3点ボタンの`bottom`値がSPサイズと若干異なります。
タブレットサイズ以降、つまりPCサイズも同様の実装でお願いします。

**Comment by uunnee** [comment]
- [ ] スライドアップしてくる3点ボタンのbottom値がSPサイズと若干異なります。

**Comment by uunnee** [comment]
@indif78 
http://static.uplink.co.jp/01_archive_film_shibuya.html
http://static.uplink.co.jp/01_archive_market_shibuya.html
サブナビに関しまして、
https://github.com/uplinkjp/uplink.co.jp/issues/41#issuecomment-439609916 の内容を調整いたしました。
ご確認お願いいたします！

**Comment by indif78** [comment]
@uunnee 
こちら調整ありがとうございます！
確認できましたのでクローズしますー
