### ISSUE TITLE
【共通】Webフォントの読み込み調整

### ISSUE THREAD

**Issue by indif78** [uplinkjp/uplink.co.jp#42]
@uunnee 
#10 で指定しているWebフォントが正しく読み込まれているか、ご確認お願いします。

特にNoto Sans JPが適用されるべき箇所がすべてフォールバック（游ゴシック）で表示されてしまっています。記述的には問題なさそうなんですが、原因を探っていただけますでしょうか。

ちなみに欧文のSpace Groteskについて、読み込むのはBoldのみでOKです。
また、OTF形式はなしで、WOFF2/WOFFの2形式のみ、この順番で設定ください。

YakuHanJPは問題なさそうです。

**Comment by uunnee** [comment]
@indif78 
失礼しました！
おおもとの読み込み記述にミスがありました…
http://static.uplink.co.jp
修正しましたので、ご確認お願いいたします。
( Space Groteskもboldのみ、形式もご指定のものに変更しました！ )

**Comment by indif78** [comment]
@uunnee 
こちら修正ありがとうございます！反映を確認しました。
サブセットの記述が必要なんですね、勉強になりました。
クローズしますー

**Comment by indif78** [comment]
@uunnee 
すみません、こちらOTF形式を切ったからなのか不明なのですが、SP/Tab実機でSpace Grotesk Bold部分が正しくレンダリングされなくなっています。こちら検証いただけますでしょうか。場合によってはOTF復活でも構いません。お手数ですが、よろしくお願いしますー

![img_2237](https://user-images.githubusercontent.com/7245445/48668239-f7e68180-eb2b-11e8-84ad-e3902443050a.PNG)

**Comment by indif78** [comment]
@uunnee 
こちら404出てますね。ご確認お願いしますー
（今までlocalのフォント読み込んでいたので気づきませんでした）

**Comment by uunnee** [comment]
@indif78 
失礼しました…どこかのタイミングでフォントファイルが消えていました。
http://static.uplink.co.jp/
アップし直しましたのでご確認お願いいたします。

**Comment by indif78** [comment]
@uunnee 
こちら修正ありがとうございます！
確認できましたのでクローズしますー
