### ISSUE TITLE
【共通】グローバルヘッダーおよびグロナビのスタイル調整

### ISSUE THREAD

**Issue by indif78** [uplinkjp/uplink.co.jp#44]
@uunnee 
グローバルヘッダーおよびグロナビについて下記スタイル調整をお願いします。

## グローバルヘッダー

- [x] 左の黒UPLINKロゴは必ず本体サイトトップへ、中央のテキストロゴは劇場の場合各劇場トップ、本体サイトは本体サイトトップへリンクさせたいです

- [x] 中央ロゴの表示位置がずれていますので、`.header-logo a:after`について`background-position: 20px center`としてください

## グロナビ

- [x] ボタンの間隔は`4px`となるようにしてください（現状5px）

- [x] ボタンの角丸サイズがデザインと異なります。`border-radius: 3px`としてください。この値はサイト上で使用するすべての角丸ボタン共通の値です。

- [x] 本体サイト「渋谷」「吉祥寺」「Cloud」ボタンについて、ロゴ画像と英語キャプションの間隔がデザインに比べて狭いので、`.nav-* a img`について`margin-bottom: 5px`としてください（これにより本体サイトトップの関連サービスエリア内ボタンについても調整が済むかと）

- [x] 本体サイト「Cloud」ボタンは関連サービスボタン扱いで背景白になっていますが、グロナビ内だけは`#e5e5e5`となるよう調整お願いします。

- [x] 劇場サイト「上映」と「イベント」ボタンのフォントサイズがデザインと異なります。`font-size: 24px`としてください。

- [x] ボタンの英語キャプションについて`letter-spacing: .025em`を追加してください。この値はフォントがSpace Groteskの場合は必ず適用させたいので、mixin「f_sg_bold」に含めてしまってもよいかもしれません。

- [x] 劇場サイトの小ボタン（グレーと黒）はアローサイズが小さくなります。`13px`四方で表示されるよう調整お願いします。

- [x] 劇場サイトのログインボタンについて、「会員ログイン」を「ログイン」としてください

- [x] デザインを参考に、Googleカスタム検索窓を追加してください

**Comment by indif78** [comment]
@uunnee 
追加いただいたGoogleカスタム検索窓について、下記スタイル調整をお願いします。

- [ ] `.form-googlesearch`について`margin-top`を削除してください

- [ ] `.form-googlesearch-text input`について`padding: 0 10px`としてくださいませ

- [ ] 検索ボタンの幅はその上にくるボタンと合わせたいので、調整（同様の`calc`処理）をお願いします（下記はiPhone8サイズでの表示例）
![uplink 2](https://user-images.githubusercontent.com/7245445/48529414-5adedb00-e8d6-11e8-859c-06a5844d406e.png)

**Comment by indif78** [comment]
@uunnee 
五月雨にすみません、下記も追加でお願いします。
ヘッダー内のロゴ（黒と個別）がクラス名同じなので、継承がちょっと怖いですね。

- [ ] ヘッダーの黒ロゴ`.header-logo`の方について`padding-right: 15px`としてください

**Comment by uunnee** [comment]
NOTE
>  劇場サイトの小ボタン（グレーと黒）はアローサイズが小さくなります。13px四方で表示されるよう調整お願いします。
ジャギるので14にした。SVGご支給いただくほうがいいかも？

**Comment by uunnee** [comment]
@indif78 
http://static.uplink.co.jp
おまとめありがとうございます。対応いたしました！

下記あわせてご確認おねがいいたします。

>  劇場サイトの小ボタン（グレーと黒）はアローサイズが小さくなります。13px四方で表示されるよう調整お願いします。

13だとジャギって見えてしまうので、14にしました…！
こちら、SVGにしたほうがよさげですよね…？
お手数ですがご判断いただき、必要でしたらSVGのご支給いただけますでしょうか。
よろしくお願いいたします！

**Comment by indif78** [comment]
@uunnee 
すません、こちら追加で、

## グロナビ

> - [x] ボタンの間隔は`4px`となるようにしてください（現状5px）

こちらすべて対応いただいたと思ったのですが、

- [ ] `.nav-wrap-child>div`の`width`設定で`calc`を使われているところがまだ`5px`間隔前提になっているもの（`calc((100% - 10px)/ 3)`など）がありそうですので、`4px`間隔前提への修正をお願いします。

**Comment by uunnee** [comment]
@indif78 
http://static.uplink.co.jp
調整いたしました。ご確認お願いいたします。

**Comment by indif78** [comment]
@uunnee 
こちら修正ありがとうございます！
確認できましたのでクローズしますー

**Comment by indif78** [comment]
@uunnee 
こちら下記追加調整をお願いします。

- [ ] 追従ヘッダーからグロナビを開いた際、ボタンのマウスホバー処理が効かないようです。検索ボタンのみ効きます。
[AwesomeScreenshot-2018-11-18T04-47-24-454Z.webm.zip](https://github.com/uplinkjp/uplink.co.jp/files/2592514/AwesomeScreenshot-2018-11-18T04-47-24-454Z.webm.zip)

**Comment by uunnee** [comment]
@indif78 
http://static.uplink.co.jp/
こちら修正いたしました！ご確認お願いいたします。

**Comment by indif78** [comment]
@uunnee 
ホバーの件、修正ありがとうございます！確認しました。
あと1点だけ、調整よろしいでしょうか。。（私からはこれで最後のはず！）

- [ ] グロナビが2行形式になるブレイクポイント`1024px`のときに「施設レンタル」ボタンだけ改行してしまうので、`.nav-login a, .theme-joji .nav-default a, .theme-shibuya .nav-default a`について`padding-right: 4px`としてください
![uplink 6](https://user-images.githubusercontent.com/7245445/48670344-a8b74580-eb59-11e8-9044-43a9ca369f03.png)

お手数ですが、よろしくお願いします。

**Comment by uunnee** [comment]
@indif78 
http://static.uplink.co.jp/01_archive_film_shibuya.html
こちらも対応完了いたしました！
お手数ですがご確認、よろしくお願いいたします。

**Comment by indif78** [comment]
@uunnee 
こちら改行の件、ご対応ありがとうございます！確認しました。

これで完了かと思ったのですが、これまでは出ていなかった下記症状がヘッダーエリアで発生するようになっていますので、お手数ですがご確認お願いします。

- [ ] ヘッダーエリアに不要な余白が生じてしまっているので、解消お願いします。
![uplink 7](https://user-images.githubusercontent.com/7245445/48937577-e77e3e80-ef51-11e8-814c-045cb6b3bcf0.png)

サイト全体で見られるようです。
開発ツールで見ると、`body`タグの中に`link`タグや`title`タグが入るようになってしまう？（ソースを開くとそうではない）など挙動が怪しいところがあります。
お手数ですが、よろしくお願いしますー

**Comment by uunnee** [comment]
@indif78 
こちらありがとうございました。
何が原因かいまいちよくわからなかったのですが、
影響していた部分を再度描き直してみたところ治ったようです…

@mcatm 
こちら、https://github.com/uplinkjp/uplink.co.jp/pull/76 にてPR出したのですが、
差分見てもいまいち原因がわからないので、バックエンド側でもし同様な現象がおきたらご相談いただければと思います。
お手数をおかけしますがよろしくお願いいたします。

**Comment by indif78** [comment]
@uunnee @mcatm 
こちら調整ありがとうございます！
staticサイトで解消されていたのを確認しましたのでクローズしますー
