### ISSUE TITLE
【共通】カルーセルエリアのスタイル調整

### ISSUE THREAD

**Issue by indif78** [uplinkjp/uplink.co.jp#45]
@uunnee 
カルーセルエリアについて下記スタイル調整をお願いします。

- [x] スライドエリアの幅はコンテナ幅と同値（`87.5vw`）になるようにしてください。

- [x] スライドエリアの高さは固定ではなく、アスペクト比が16:9で保たれるようにしてください。（`padding-top: 56.25%`として、中の要素を絶対位置で配置するなど）

- [x] スライドの間隔はボタンと同様に`4px`となるようにしてください

- [x] スライド内の画像は`background-size: contain`的に表示されるようにしてください

- [x] スライド内の上下テキストエリア高とフォントサイズはSPとTab/PCで異なります。SPでは`height: 24px`、上は`font-size: 11px`下は`font-size: 12px`となるようにしてください（Tab/PCは現状の`height: 30px`、上は`font-size: 12px`下は`font-size: 15px`でOKです）

- [x] インジケータードットの間隔がデザインと異なります。`.slick-dots li`について`margin: 0 5px`としてください。

- [x] スライドの自動再生（間隔は4秒）をお願いします。

**Comment by uunnee** [comment]
NOTE

> スライド内の画像はbackground-size: contain的に表示されるようにしてください

適正な画像サイズがアップされればその表示になるが、拡大してでもcontain的にしたほうがいいか？確認

**Comment by uunnee** [comment]
@indif78 
http://static.uplink.co.jp/00_index_shibuya.html
http://static.uplink.co.jp/00_index_joji.html
対応いたしました！

> スライド内の画像はbackground-size: contain的に表示されるようにしてください

こちらなのですが、現状、画像サイズが枠以上のものはcontain的に表示されるようになってます。
( 画像の原寸サイズ以上の拡大はされず、小さい場合は中心に表示 )
なので運用で大きいサイズをあげていただければと思ったのですが、
画像の原寸を超えたサイズにも拡大したほうがいいでしょうか。

ご確認お願いいたします。

**Comment by indif78** [comment]
@uunnee 
こちらもご対応ありがとうございます！確認しました。
まず、

> こちらなのですが、現状、画像サイズが枠以上のものはcontain的に表示されるようになってます。

こちら理解しました。小さいサイズのものは原寸が最大になるのでOKです（拡大不要）。

そして下記について調整をお願いできますでしょうか。

> - [x] スライドエリアの幅はコンテナ幅と同値（`87.5vw`）になるようにしてください。

すみません、こちら私の伝え方が諸々間違っておりました。。
正しくは「スライド」の幅を「グロナビ幅」に合わせたい、でした。

さらに、

> - [x] スライドエリアの高さは固定ではなく、アスペクト比が16:9で保たれるようにしてください。

これも「スライドエリア」＝「スライド」でした。。

なので、

- [ ] `.l-slider .slider-inner .slick-slide`が`padding-top: 56.25%; width: calc(87.5vw - 30px); height: 0`

的な感じになりますでしょうか。

スライドエリア自体はデザイン通りViewport幅一杯で、左右のスライドが見切れる形になるという想定です。

そしてもう1点、

- [ ] contain的な仕様にはしていただいているものの、上下黒帯分は最大幅・高を削っていただいているかと思いますが、この処理は不要ですので`.l-slider .slider-inner .slick-slide img`について`max-width: 100%; max-height: 100%`としてください

以上お手数をおかけしますが、よろしくお願いいたします！

**Comment by uunnee** [comment]
@indif78 
調整しました！
http://static.uplink.co.jp/00_index_shibuya.html
http://static.uplink.co.jp/00_index_joji.html

**Comment by indif78** [comment]
@uunnee 
こちら調整ありがとうございます！素敵です。
確認できましたのでクローズしますー
