### ISSUE TITLE
【共通】お知らせ一覧のスタイル調整

### ISSUE THREAD

**Issue by indif78** [uplinkjp/uplink.co.jp#47]
@uunnee 
お知らせ一覧について、下記スタイル調整をお願いします。

## トップページ系（テキストリンクのみ）

- [x] リスト要素`.list-news li`の間隔もグロナビボタンと同じです。`margin-bottom: 4px`としてください

- [x] モアボタン`.list-readmore`についても`margin-top: 4px`としてください。こちらはサイト共通でお願いします。

- [x] 日付`.list-news-date`はSpece Grotesk Boldがあたるようにしてください

- [x] 同要素について`margin-bottom`を省いてください

- [x] NEWラベル`.list-news-date span`について`color: #FF1744`としてください

## アーカイブ系（テキストリンク＋サムネイル）

- テキストリンク部分のスタイルはトップページ系の値を継承

- [x] `.list-news-thumb`について`margin-left`を削除し、SPサイズでは`width: 90px`、Tab/PCサイズでは`width: 168px`と固定にしてください

- [x] ページャー`.archive-pager`について`margin: 4px 0 0`としてください（サイト共通）

**Comment by uunnee** [comment]
@indif78 
おまとめありがとうございます！
http://static.uplink.co.jp/00_index.html
http://static.uplink.co.jp/00_index_shibuya.html
http://static.uplink.co.jp/00_index_joji.html
http://static.uplink.co.jp/01_archive_news_shibuya.html
修正対応いたしました。

**Comment by indif78** [comment]
@uunnee 
こちらご対応ありがとうございます！
確認できましたのでクローズしますー
