### ISSUE TITLE
【共通】グロナビがfixedになるタイミング？で画面がカクンとなる

### ISSUE THREAD

**Issue by indif78** [uplinkjp/uplink.co.jp#48]
下記添付録画のように、グロナビがfixedになるタイミング？で画面がカクンとなるのを解消したいです。
トップページ系でスクロール位置がグロナビエリアを超えるタイミングで発生します。
（`.js-headerWrap`に`.is-scroll`が付くタイミング）
お手数ですが、調整のほどお願いいたします。

[AwesomeScreenshot-2018-11-12T08-02-15-190Z.webm.zip](https://github.com/uplinkjp/uplink.co.jp/files/2571063/AwesomeScreenshot-2018-11-12T08-02-15-190Z.webm.zip)

**Comment by uunnee** [comment]
NOTE
setsize()を復活

**Comment by indif78** [comment]
@uunnee 
こちら解消ありがとうございます！
確認できましたのでクローズしますー
