### ISSUE TITLE
【劇場系】スケジュールエリアのスタイル調整

### ISSUE THREAD

**Issue by indif78** [uplinkjp/uplink.co.jp#49]
@uunnee 
スケジュールエリアについて、下記スタイル調整をお願いします。

- [x] カテゴリタグ`.tag-*`について`padding: 0 6px`としてください

- [x] カレンダーヘッダー`.list-calendar-header`について`margin: 0 0 4px; padding: 16px 15px`としてください

- [x] `.list-calendar li`について`margin-bottom: 4px; padding: 15px`としてください

- [x] `.list-calendar-inner`について`padding: 10px`としてください

- [x] `.list-calendar-date`について`margin: 0 0 5px`としてください

- [x] `.button-purchase`について`height: 34px`としてください

- [x] `.button-purchase a`について`height: 34px; line-height: 34px; padding: 0 0 0 28px;`

- [x] PC版で2カラムになる際の左カラム幅は固定幅ではなく`25%`と相対値にしてください（現状`.list-calendar-header`で設定している値）

- [x] PC版で2カラムになる際の右カラム`.list-calendar`について`margin-left: 4px`としてください

**Comment by indif78** [comment]
@uunnee 
スケジュールアーカイブページのスタイル調整もこちらにまとめます。

- [ ] `.header_sub-heading span`（MONTHLY SCHEDULE）の末尾に不要な「L」が入ってしまっていますので、削除お願いします。

- [ ] `.archive_shcedule-header`について`padding: 20px 15px`としてください

- [ ] `.archive_header-heading`はSpace Grotesk Boldが適用されるようにしてください

- [ ] `.archive_header-nav a`は透過不要です。通常リンクテキストとして`color: #007B7B`としてください

- [ ] `.archive_header-nav>*`について`margin-left: 10px`としてください

**Comment by uunnee** [comment]
@indif78 
おまとめありがとうございます！！！
http://static.uplink.co.jp/00_index.html
http://static.uplink.co.jp/00_index_shibuya.html
http://static.uplink.co.jp/00_index_joji.html
http://static.uplink.co.jp/04_schedule_shibuya.html
調整対応いたしました。ご確認お願いいたします。

**Comment by indif78** [comment]
@uunnee 
こちら調整ありがとうございます！上記反映確認できました。

下記、お手数ですが当初未実装だったsticky部分と、スケジュールエリアのセクションタイトル（通常のものとスケジュールヘッダー）のTab/PCレイアウトについて漏れがありましたので追加調整をお願いします。

- [ ] stickyバーよりボタンが上に表示されてしまいますので、下に潜るよう`z-index`の調整をお願いします。
![static uplink co jp_04_schedule_shibuya html iphone 5_se](https://user-images.githubusercontent.com/7245445/48497109-dad55880-e876-11e8-9fb5-05ab91fa01a9.png)

- [ ] スケジュールエリアのセクションタイトル（通常のものとスケジュールヘッダー）はTab/PCでラベルエリアとで2カラムレイアウトになります。スケジュールヘッダーについてはデザインイメージがなかったので、下記へ追加しています。お手数ですが、こちらの内容で調整お願いします。スケジュールヘッダーについては留意点として、SP版では月表示とナビリンクがそれぞれコンテナ内の左右に振られる（`space-between`的）のに対して、Tab/PCでは左揃え（`flex-start`的）になるイメージです。
https://drive.google.com/drive/folders/1j9RN5Q1Usphph6lAOD0Bb7iDmsRJFvWE

**Comment by indif78** [comment]
@uunnee 
こちらご対応ありがとうございます！反映確認できましたのでクローズしますー
