### ISSUE TITLE
ロゴのレギュレーションについて

### ISSUE THREAD

**Issue by indif78** [uplinkjp/uplink.co.jp#5]
@UPLINK-OhbaKomugi @mcatm 
UPLINKロゴはじめ、ご支給いただいたロゴについて、レギュレーションがありましたら共有くださいませ。資料という形式でない場合は、こちらに箇条書きいただく形でも結構です。

現状気になっている点は：

- UPLINKロゴ（上にバツ印、下にロゴタイプのもの）について、バツ印のみでの使用は可能か

です。

お手数ですが、ご確認のほどよろしくお願いいたします。

**Comment by uplinkKMG** [comment]
ロゴ全体をグラフィティぽくする、線をラフにするのはOKですが。分解は基本的にはNGです。

**Comment by indif78** [comment]
@uplinkKMG 
早速のご回答ありがとうございます！承知いたしました。
