### ISSUE TITLE
【共通】SNS・メルマガエリアのスタイル調整

### ISSUE THREAD

**Issue by indif78** [uplinkjp/uplink.co.jp#50]
@uunnee 
フッター上のSNS・メルマガエリアについて、下記スタイル調整をお願いします。

- [x] `.followus-inner`について`padding: 40px 15px`としてください

- [x] 「メールマガジン登録」リンクテキストについて`font-weight: 700`としてください

**Comment by uunnee** [comment]
@indif78 
http://static.uplink.co.jp/
調整いたしました！ご確認おねがいいたします。

**Comment by indif78** [comment]
@uunnee 
こちら調整ありがとうございます！
反映確認できましたのでクローズしますー
