### ISSUE TITLE
【共通】グローバルフッターのスタイル調整

### ISSUE THREAD

**Issue by indif78** [uplinkjp/uplink.co.jp#51]
@uunnee 
グローバルフッターについて、下記スタイル調整をお願いします。

- [x] UPLINKロゴ`.footer-logo img`について`width: 60px`としてください

**Comment by uunnee** [comment]
@indif78 
http://static.uplink.co.jp/
こちらも調整いたしました！ご確認おねがいいたします。

**Comment by indif78** [comment]
@uunnee 
こちら調整ありがとうございます！
反映確認できましたのでクローズしますー
