### ISSUE TITLE
【本体サイト】グロナビエリアの背景色

### ISSUE THREAD

**Issue by indif78** [uplinkjp/uplink.co.jp#52]
@uunnee 
本体サイトのグロナビエリアは背景色が黒ですが、その背景色のみ画面幅一杯になるようにしてください。
（下記添付画像の赤枠部分も黒くなる感じです）

![uplink](https://user-images.githubusercontent.com/7245445/48337504-6ea3fa80-e6a6-11e8-9946-7ab7346f9dbf.png)

**Comment by uunnee** [comment]
@indif78 
こちら調整かけております！
ご確認おねがいいたします。

**Comment by indif78** [comment]
@uunnee 
すみませんこちら齟齬があるようです。

> （下記添付画像の赤枠部分も**黒くなる**感じです）

黒い背景色が幅一杯になる、という意です〜。
お手数ですが、改めて調整のほどお願いいたします。

**Comment by uunnee** [comment]
@indif78 
大変失礼いたしました！
グロナビ改修時にまた消えてしまってました…
http://static.uplink.co.jp/00_index.html
再度調整しましたので、お手数ですがご確認お願いいたします。

**Comment by indif78** [comment]
@uunnee 
こちらご対応ありがとうございます！反映確認できましたのでクローズしますー
