### ISSUE TITLE
【共通】サイト共通のトランジション設定が反映されていない

### ISSUE THREAD

**Issue by indif78** [uplinkjp/uplink.co.jp#53]
@uunnee 
グロナビ開閉時など、本サイトで発生する各種トランジションには #11 の値を設定するようお願いします。

**Comment by uunnee** [comment]
@indif78 
http://static.uplink.co.jp/
こちら対応いたしました！
ご確認お願いいたします。

**Comment by indif78** [comment]
@uunnee 
こちらご対応ありがとうございます！反映確認できましたのでクローズしますー
（`transition-duration`については要素によって調整いただくかもしれません。その際は都度お知らせします）
