### ISSUE TITLE
【共通】上映トップなどカード型一覧ページのスタイル調整

### ISSUE THREAD

**Issue by indif78** [uplinkjp/uplink.co.jp#54]
@uunnee 
上映トップなどカード型一覧ページについて、下記スタイル調整をお願いします。

- [x] SP版（1カラム）でカードの左右に余白が必要です。`.list_archive-item`について`width: 100%`を省き、`margin: 0 15px 20px`としてください。またそれにより、Tab/PC版（2カラム、3カラム）の調整が必要かと思いますのでご確認の上お願いします。

- [x] `.list_archive-thumb`について`padding-top: 42.5%`としてください

- [x] サムネイル画像は`background-size: cover; background-position: center`の挙動を想定しています。背景画像での実装が可能であればお願いします

- [x] `.list_archive-heading`について`padding: 10px 10px 5px`としてください

- [x] `.list_archive-text`について`color: rgba(0,0,0,.6)`（セカンダリーテキストカラー）としてください

**Comment by uunnee** [comment]
サムネイル画像はbackground-size: cover; background-position: centerの挙動を想定しています。背景画像での実装が可能であればお願いします

**Comment by uunnee** [comment]
@indif78 
http://static.uplink.co.jp/01_archive_event_shibuya.html
http://static.uplink.co.jp/01_archive_film_shibuya.html
http://static.uplink.co.jp/01_archive_gallery_shibuya.html
http://static.uplink.co.jp/01_archive_market_shibuya.html
こちら対応いたしました！
ご確認お願いいたします。

**Comment by indif78** [comment]
@uunnee 
こちらご対応ありがとうございます！反映確認できましたのでクローズしますー
