### ISSUE TITLE
【共通】表示モード切替時やリサイズ時のケア

### ISSUE THREAD

**Issue by indif78** [uplinkjp/uplink.co.jp#56]
@uunnee 
スマホファーストなサイトでもあるので、表示モード（ポートレート／ランドスケープ）切替時の機能維持や崩れを最小限に抑えたいところです。
気になった箇所をこちらへ挙げていきますので、リサイズ時の再計算などケアをご検討お願いします。

- [x] トップページ系のファーストビュー（グロナビ表示）
[AwesomeScreenshot-2018-11-15T01-39-29-792Z.webm.zip](https://github.com/uplinkjp/uplink.co.jp/files/2583304/AwesomeScreenshot-2018-11-15T01-39-29-792Z.webm.zip)

- [x] 下層ページでのファーストビュー（グロナビ・ページタイトル・サブナビ）
[AwesomeScreenshot-2018-11-14T16-04-39-823Z.webm.zip](https://github.com/uplinkjp/uplink.co.jp/files/2583291/AwesomeScreenshot-2018-11-14T16-04-39-823Z.webm.zip)

- [x] スケジュールエリアのsticky（下記iPadサイズでの例）
[AwesomeScreenshot-2018-11-15T01-43-16-046Z.webm.zip](https://github.com/uplinkjp/uplink.co.jp/files/2583313/AwesomeScreenshot-2018-11-15T01-43-16-046Z.webm.zip)

**Comment by uunnee** [comment]
NOTE
resizeイベントを復活

**Comment by indif78** [comment]
@uunnee 
こちら調整ありがとうございます！とてもいい感じです！
下記sticky部分のみ、見ていただくこと可能でしょうか？

- [ ] スケジュールエリアがあるページ（トップ・スケジュール）でタブレットサイズのポートレートモードからランドスケープモードへ切り替えて閲覧した際にsticky部分がおかしくなるようです（下記キャプチャ参照）。そもそもiPad実機およびChrome DevツールのiPadランドスケープモードでstickyが動いていない？ようなので関係があるかもしれません。お手数ですが検証のほどよろしくお願いします。
[AwesomeScreenshot-2018-11-18T02-54-31-017Z.webm.zip](https://github.com/uplinkjp/uplink.co.jp/files/2592480/AwesomeScreenshot-2018-11-18T02-54-31-017Z.webm.zip)

**Comment by indif78** [comment]
@uunnee 
こちらアサイン抜けていたっぽんですが、ご対応いただいた感じですかね？
念のためご確認お願いします〜

**Comment by uunnee** [comment]
@indif78 
http://static.uplink.co.jp/04_schedule_shibuya.html
こちら調整済ですー！
ご確認よろしくお願いいたします。

**Comment by indif78** [comment]
@uunnee 
ありがとうございます！
確認できましたのでクローズしますー
