### ISSUE TITLE
【共通】ヘッダー・サブヘッダーの縦ライン

### ISSUE THREAD

**Issue by indif78** [uplinkjp/uplink.co.jp#57]
@uunnee 
SPサイズは問題ないですが、Tab/PCにおいて、ヘッダー・サブヘッダーの縦ライン（ブロックとテキストなど内包要素の配置位置）が想定と異なりますので、下記画像をご参照の上調整をお願いします。コンテンツエリアの内包要素と頭が揃うイメージです。

## デザイン想定

<img width="1375" alt="2018-11-15 11 22 10" src="https://user-images.githubusercontent.com/7245445/48525998-61b32100-e8c9-11e8-814a-22d893a34e9e.png">

## 現状

![uplink 1](https://user-images.githubusercontent.com/7245445/48526163-00d81880-e8ca-11e8-8809-581f9a261b18.png)

**Comment by uunnee** [comment]
@indif78 
http://static.uplink.co.jp
こちら調整いたしました！
ご確認よろしくお願いいたします。

**Comment by indif78** [comment]
@uunnee 
こちら調整ありがとうございます！
確認できましたのでクローズしますー
