### ISSUE TITLE
【共通】サブナビ追従ボタンの表示タイミング

### ISSUE THREAD

**Issue by indif78** [uplinkjp/uplink.co.jp#58]
@uunnee 
サブナビがあるページで、スクロール時にサブナビボタンを追従させますが、その表示タイミングが想定と異なりますので調整をお願いします。

仕様 #41 をおさらいすると：

> ## Viewport内にページヘッダーが表示されていない場合（uplink_subnav_3）
> 
> - サブナビがあるページを表示（uplink_subnav_1）
> - スクロールダウン（uplink_subnav_2）
> - ページヘッダーがViewportの外へ出たタイミングで画面下から三点ボタンがスライドアップ（uplink_subnav_3）
> - その三点ボタンをタップすると（uplink_subnav_4）
> - 画面下からサブナビを含むページヘッダーエリアがスライドアップ（中身はフェードイン）し、画面上からはグローバルヘッダーがスライドダウン（uplink_subnav_5）
> - トランジション完了（uplink_subnav_6）

となるのが理想です。
現状の実装では：

> - ページヘッダーがViewportの外へ出たタイミングで画面下から三点ボタンがスライドアップ（uplink_subnav_3）

とならず、スクロールアップした際にヘッダーとともに表示される形になってしまっています。
お手数ですが、調整をお願いします。

**Comment by indif78** [comment]
@uunnee 
追記ですみません、下から出現するサブナビボタンについてはスペックデザインにあるシャドウ`box-shadow: 0 4px 32px rgba(0,0,0,.4)`を付与いただけますでしょうか？お手数ですが、よろしくお願いします。

https://drive.google.com/drive/folders/1fI41UsmKLB5v3LiW5ZOIZq_cTdE3mONr

![uplink_subnav_3](https://user-images.githubusercontent.com/7245445/48530848-0ab74700-e8dd-11e8-93a7-d7dfa15c5ddc.jpg)

**Comment by uunnee** [comment]
- [ ] ページヘッダーがViewportの外へ出たタイミングで画面下から三点ボタンがスライドアップ（uplink_subnav_3）
- [ ] 固定サブボタン `box-shadow: 0 4px 32px rgba(0,0,0,.4)`

**Comment by uunnee** [comment]
@indif78
http://static.uplink.co.jp/01_archive_film_shibuya.html
http://static.uplink.co.jp/01_archive_market_shibuya.html
こちらも、サブナビに関しまして、
https://github.com/uplinkjp/uplink.co.jp/issues/58#issuecomment-439609900 の内容を調整いたしました！
ご確認お願いいたします！

**Comment by indif78** [comment]
@uunnee 
こちら調整ありがとうございます！
確認できましたのでクローズしますー
