### ISSUE TITLE
【共通】サブナビエリアのスタイル調整

### ISSUE THREAD

**Issue by indif78** [uplinkjp/uplink.co.jp#59]
@uunnee 
サブナビエリアについて、下記スタイル調整をお願いします。

- [x] `.l-nav_sub a`について`border-width: 1px; border-color: rgba(255, 255, 255, .12)`としてください

- [x] すみません、SPサイズでの最下部罫線`.l-nav_sub a:last-child`はトリにしようと思います。関連記述の削除をお願いします

**Comment by uunnee** [comment]
@indif78 
http://static.uplink.co.jp
こちら調整いたしました。
ご確認よろしくお願いいたします。

**Comment by indif78** [comment]
@uunnee 
こちら調整ありがとうございます！
確認できましたのでクローズしますー

**Comment by indif78** [comment]
@uunnee 
すみません、こちら下記追加で調整をお願いできますでしょうか。
お手数をおかけしますが、よろしくお願いいたします。

- [ ] サブナビボタンの表示位置がグロナビボタンと中央揃えになるようにしてください（リキッドレイアウトな部分もあると思うので、難しい場合は大体でOKです）
![uplink 5](https://user-images.githubusercontent.com/7245445/48668692-582ef080-eb37-11e8-81be-46e4d3fedf1c.png)

**Comment by uunnee** [comment]
@indif78 
こちら調整してみましたのでご確認お願いします。
http://static.uplink.co.jp/01_archive_film_shibuya.html

**Comment by indif78** [comment]
@uunnee 
こちら調整ありがとうございます！いい感じです！

- [ ] ウィンドウ下に表示されるクローンサブナビ内の3点ボタン`.is-clone .header-nav_sub_trigger`も同様に調整お願いします

**Comment by uunnee** [comment]
@indif78 
こちらも対応しました！
http://static.uplink.co.jp/01_archive_film_shibuya.html
ご確認よろしくお願いいたします。

**Comment by indif78** [comment]
@uunnee 
こちらご対応ありがとうございます！
確認できましたのでクローズしますー
