### ISSUE TITLE
bodyのclassまとめ

### ISSUE THREAD

**Issue by uunnee** [uplinkjp/uplink.co.jp#61]
### メインナビ / カラーテーマに関するもの
全ページ、必ず当てはまるものを一つ付与

- `.theme-main` : 本体サイト
- `.theme-shibuya` : 渋谷サイト
- `.theme-joji` : 吉祥寺サイト

### サブナビ / カラーテーマに関するもの
2階層目以下で、下記のうち、当てはまるものをひとつ付与

- `.category-event` : イベント
- `.category-film` : 上映
- `.category-gallery` : ギャラリー
- `.category-market` : マーケット
- `.category-default` : 上記以外 ( グレー背景 )

### デフォルトのナビの開き方などを設定するためのもの
全ページ、必ず当てはまるものを一つ付与 ( https://github.com/uplinkjp/uplink.co.jp/issues/32 に利用 )

- `.type-frontpage` : フロントページ
- `.type-2nd` : 2階層目 ( アーカイブまわりとか )
- `.type-3rd` : 3階層目 ( single / pageとか )

### JSで付与されるクラス
バックエンド側で競合してしまう場合は調整しますのでおっしゃってください。

- `.is-scroll`
- `.is-fixed`
- `.is-navfixed`
- `.is-subNavTriggerFix`
- `.main-open`
- `.sub-open`

**Comment by uunnee** [comment]
@mcatm 
こちら、グロナビの修正によってbody classが変更になるかもしれないので、
FIX次第アサインふらせていただきます！

**Comment by uunnee** [comment]
@mcatm 
上記で確定になりそうですのでご確認よろしくお願いいたします。

**Comment by mcatm** [comment]
@uunnee 
了解ですー。ありがとうございます。
