### ISSUE TITLE
favicon / apple-touch-iconの設定

### ISSUE THREAD

**Issue by indif78** [uplinkjp/uplink.co.jp#63]
@uunnee 
favicon / apple-touch-icon 画像を下記へ用意しました。
お手数ですが、実装のほどお願いいたします。

https://drive.google.com/drive/folders/1iJt5XFvH_HEb-dYBwGpxCb8N4_soraIG

**Comment by uunnee** [comment]
@indif78 
こちらお待たせいたしました！
http://static.uplink.co.jp/00_index.html
http://static.uplink.co.jp/00_index_shibuya.html
http://static.uplink.co.jp/00_index_joji.html
favicon / apple-touch-icon を実装いたしました。
ご確認お願いいたします！

@mcatm 
後ほどPRを出しますが、
head内該当部分のバックエンド対応お願いいたします。
画像は、/img/icon/以下におきました！

**Comment by indif78** [comment]
@uunnee 
こちらご対応ありがとうございます！確認できました。

@mcatm 
ご確認いただけましたら適宜クローズお願いしますー

**Comment by mcatm** [comment]
@indif78 @uunnee 
仕込みました！閉じます！
