### ISSUE TITLE
og:image の設定

### ISSUE THREAD

**Issue by indif78** [uplinkjp/uplink.co.jp#64]
@uunnee 
デフォルト og:image 画像を下記へ用意しました。
お手数ですが、実装のほどお願いいたします。

https://drive.google.com/drive/folders/1QEpR2eyWaBUf4Wx3INaXoyqTN6U85FVn

@mcatm 
ニュース記事や上映作品など、アイキャッチが設定されている場合はそちらが適用される想定ですかね。
ご確認のほどお願いします〜

**Comment by mcatm** [comment]
@indif78 @uunnee 
こちら、俺の方で実装するので問題ないですー。

@indif78 
詳細ページはアイキャッチを使います！

**Comment by indif78** [comment]
@mcatm 
承知しました！よろしくお願いしますー

**Comment by mcatm** [comment]
@indif78 
設定しましたー。管理画面から設定するタイプなので、本体＋渋谷で設定したら閉じます。

![2018-11-28 00 03 57](https://user-images.githubusercontent.com/292807/49090466-1faeb580-f2a1-11e8-9feb-08cc94e2eed8.png)

**Comment by indif78** [comment]
@mcatm 
ありがとうございますー。よろしくお願いします
