### ISSUE TITLE
【Design】No Image

### ISSUE THREAD

**Issue by mcatm** [uplinkjp/uplink.co.jp#74]
@indif78 
すみません！No Imageの設定を忘れていました。
こちら、対応可能でしょうか？？

**Comment by indif78** [comment]
@mcatm 
こちらご指摘ありがとうございます！ご用意しますー

**Comment by indif78** [comment]
@mcatm 
取り急ぎこちらでお願いします〜
https://drive.google.com/drive/folders/1X0-4wDnzRfV-nhZZCujKuUTACuVLPS85
![no-image](https://user-images.githubusercontent.com/7245445/49025479-1f4de600-f1df-11e8-99ef-de55d300467e.png)

@uplinkKMG 
レギュレーション的に問題ありそうでしたらご指摘くださいませ

**Comment by mcatm** [comment]
@uplinkKMG 
仕込みましたー。確認お願いします！

![2018-11-29 23 09 39](https://user-images.githubusercontent.com/292807/49227207-e35b9080-f42b-11e8-8d66-c513ec29f723.png)
