### ISSUE TITLE
【Front】劇場サイトの「購入ボタン」「△」の状態の色変更

### ISSUE THREAD

**Issue by mcatm** [uplinkjp/uplink.co.jp#91]
現状灰色のものをピンクに変更お願いします。

![購入ボタン](https://user-images.githubusercontent.com/292807/62361959-fabcc180-b556-11e9-9d5e-cb2459ce37c6.jpg)

**Comment by mcatm** [comment]
@uplinkKMG 
こんな感じで修正しました。

![スクリーンショット 2019-08-13 19 02 24](https://user-images.githubusercontent.com/292807/62934291-1f3e5680-bdff-11e9-8515-b9f36ca257c6.png)

**Comment by uplinkKMG** [comment]
問題ないです。ありがとうございます。
