### ISSUE TITLE
【Front】plan go閉鎖に伴いUPLINKのindexからリンク削除

### ISSUE THREAD

**Issue by mcatm** [uplinkjp/uplink.co.jp#92]
![1564365987911](https://user-images.githubusercontent.com/292807/62362028-1b851700-b557-11e9-8fad-5bbc74fd938b.jpg)

**Comment by mcatm** [comment]
@uplinkKMG 
対応しましたー。ここだけ？
https://stg-uplink.directorz.jp/

**Comment by uplinkKMG** [comment]
こちら取り急ぎこの個所だけになるのでOKです。ありがとうございます！
